### ISSUE TITLE
Possible Alternative for Binary Serializer

### ISSUE THREAD

**Issue by BlackCentipede** [tony-dinucci/Ovule.Nomad#1]
BinaryFormatter provided in .Net Framework tends to be slow and bloated as opposed to variety of other binary serialization methods so an alternative will be necessary for performance reasons. I would like to suggest NetSerializer2 project as an alternative which is located here: https://github.com/smalinin/netserializer2 for network based binary serialization.

I am attempting a fork to compare the performance difference between the two with Ovule.Nomad project.

**Comment by tony-dinucci** [comment]
Thanks for the suggestion :) I did actually play around with netserialiser (and a lot of others like protobuf-net, ServiceStack, etc.) - you are of course right about the binary serialiser.  Unfortunately no existing option is perfect and I'm thinking I'll have to end up doing something specially for this project.  If you're interested in helping I'd be delighted ;)  I'm thinking something based on the BinaryFormatter that doesn't go to the level of private fields and things could be good - source if obviously open now for this so shouldn't be to hard!

In actual fact just now with Nomad you can use the faster DataContract serialiser however in order to do this you'll have to create a custom implementation of  Ovule.Nomad.Wcf.IWcfKnownTypeProvider and ensure that the assembly you implement this in is both on the client and the server.  

By default things fall back to the BinaryFormatter because it can pretty much handle anything.  I wanted to allow people to get up and running very quickly and then worry about performance and stuff later.

I'll get a page put up on the Wiki about serialisation very soon as it's obviously an important issue. 

Thanks again

**Comment by BlackCentipede** [comment]
Interesting! Thank you for the reply, I'm looking forward to reading that wiki.
